"""
AI-Powered Presentation Generator using Azure OpenAI.

This module uses LLMs to intelligently analyze data, plan slide structures,
generate narratives, and create compelling presentations.
"""
import os
import json
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from enum import Enum

logger = logging.getLogger(__name__)


class VisualizationType(str, Enum):
    """Types of visualizations that can be generated."""
    BAR_CHART = "bar_chart"
    PIE_CHART = "pie_chart"
    LINE_CHART = "line_chart"
    TABLE = "table"
    BULLET_POINTS = "bullet_points"
    KPI_CARDS = "kpi_cards"
    TIMELINE = "timeline"


class SlideContent(BaseModel):
    """Content for a single slide."""
    title: str = Field(description="Compelling slide title")
    subtitle: Optional[str] = Field(default=None, description="Optional subtitle")
    narrative: Optional[str] = Field(default=None, description="Key narrative or insight for this slide")
    talking_points: List[str] = Field(default_factory=list, description="Bullet points or talking points")
    visualization_type: VisualizationType = Field(description="Best visualization for this data")
    visualization_data_key: Optional[str] = Field(default=None, description="Key in the data to visualize")
    insight: Optional[str] = Field(default=None, description="Key insight or takeaway from this slide")


class PresentationPlan(BaseModel):
    """Complete presentation plan generated by AI."""
    executive_summary: str = Field(description="Executive summary for the presentation")
    key_message: str = Field(description="The one key message the audience should remember")
    recommended_slide_count: int = Field(description="Recommended number of slides")
    slides: List[SlideContent] = Field(description="Planned slides with content")
    closing_recommendations: List[str] = Field(default_factory=list, description="Actionable recommendations")


class DataInsight(BaseModel):
    """Insight extracted from data analysis."""
    metric_name: str = Field(description="Name of the metric or data point")
    current_value: str = Field(description="Current value formatted for display")
    trend: Optional[str] = Field(default=None, description="Trend direction: up, down, stable")
    insight: str = Field(description="What this metric means for the business")
    priority: str = Field(description="Priority: high, medium, low")


class DataAnalysis(BaseModel):
    """Analysis of a data collection."""
    summary: str = Field(description="Brief summary of what this data shows")
    key_insights: List[DataInsight] = Field(description="Key insights from the data")
    best_visualization: VisualizationType = Field(description="Best way to visualize this data")
    chart_title: str = Field(description="Recommended chart/table title")
    story: str = Field(description="The story this data tells")


class AIGenerator:
    """AI-powered presentation content generator."""

    def __init__(self):
        self.endpoint = os.environ.get("AZURE_OPENAI_ENDPOINT", "")
        self.api_key = os.environ.get("AZURE_OPENAI_API_KEY", "")
        self.deployment = os.environ.get("AZURE_OPENAI_GPT_DEPLOYMENT", "gpt-4o")
        self._client = None

    def _get_client(self):
        """Get or create OpenAI client."""
        if self._client is None:
            if not self.endpoint or not self.api_key:
                raise ValueError("Azure OpenAI endpoint and API key are required")

            from openai import AzureOpenAI
            self._client = AzureOpenAI(
                azure_endpoint=self.endpoint,
                api_key=self.api_key,
                api_version="2024-08-01-preview"
            )
        return self._client

    async def analyze_data(self, data_collection: Dict[str, Any], context: Dict[str, Any]) -> DataAnalysis:
        """Analyze a data collection and extract insights."""
        client = self._get_client()

        prompt = f"""Analyze this data collection for a business presentation.

PRESENTATION CONTEXT:
Title: {context.get('title', 'Business Presentation')}
Purpose: {context.get('context', 'Executive presentation')}

DATA COLLECTION:
Title: {data_collection.get('title', 'Data')}
Source: {data_collection.get('source_type', 'unknown')}
Data: {json.dumps(data_collection.get('data', {}), indent=2)[:3000]}

Analyze this data and provide:
1. A brief summary of what the data shows
2. Key insights with business implications
3. The best visualization type for this data
4. A compelling chart/table title
5. The story this data tells

Consider the audience (executives) and focus on actionable insights."""

        response = client.beta.chat.completions.parse(
            model=self.deployment,
            messages=[
                {"role": "system", "content": "You are a data analyst creating executive presentations. Focus on insights, trends, and actionable recommendations. Be concise and impactful."},
                {"role": "user", "content": prompt}
            ],
            response_format=DataAnalysis,
            temperature=0.7
        )

        return response.choices[0].message.parsed

    async def plan_presentation(
        self,
        context: Dict[str, Any],
        data_collections: List[Dict[str, Any]],
        data_analyses: List[DataAnalysis]
    ) -> PresentationPlan:
        """Plan the complete presentation structure."""
        client = self._get_client()

        # Prepare analyses summary
        analyses_summary = []
        for i, (collection, analysis) in enumerate(zip(data_collections, data_analyses)):
            analyses_summary.append({
                "collection_title": collection.get("title"),
                "summary": analysis.summary,
                "key_insights": [ins.insight for ins in analysis.key_insights[:3]],
                "best_viz": analysis.best_visualization,
                "story": analysis.story
            })

        prompt = f"""Create a compelling executive presentation plan.

PRESENTATION CONTEXT:
Title: {context.get('title', 'Business Presentation')}
Subtitle: {context.get('subtitle', '')}
Purpose/Audience: {context.get('context', 'Executive presentation')}

DATA ANALYSES:
{json.dumps(analyses_summary, indent=2)}

Create a presentation plan that:
1. Tells a coherent story across all slides
2. Leads with the most important insights
3. Uses appropriate visualizations for each data type
4. Includes an executive summary
5. Ends with clear recommendations

The presentation should be concise (typically 5-10 slides) and impactful.
Each slide should have a clear purpose and insight.

Available visualization types: bar_chart, pie_chart, line_chart, table, bullet_points, kpi_cards, timeline"""

        response = client.beta.chat.completions.parse(
            model=self.deployment,
            messages=[
                {"role": "system", "content": "You are an expert presentation designer creating executive presentations. Focus on storytelling, visual impact, and actionable insights. Every slide should have a clear purpose."},
                {"role": "user", "content": prompt}
            ],
            response_format=PresentationPlan,
            temperature=0.7
        )

        return response.choices[0].message.parsed

    async def generate_slide_content(
        self,
        slide_plan: SlideContent,
        data: Dict[str, Any],
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Generate detailed content for a single slide."""
        client = self._get_client()

        prompt = f"""Generate detailed content for this presentation slide.

SLIDE PLAN:
Title: {slide_plan.title}
Visualization: {slide_plan.visualization_type}
Narrative: {slide_plan.narrative or 'Not specified'}
Data Key: {slide_plan.visualization_data_key or 'Full data'}

AVAILABLE DATA:
{json.dumps(data, indent=2)[:2000]}

PRESENTATION CONTEXT:
{context.get('context', 'Executive presentation')}

Generate:
1. A refined, compelling title (if the current one can be improved)
2. 3-5 concise talking points that tell a story
3. A key insight callout (one sentence)
4. Any annotations or highlights for the visualization

Keep content executive-level: concise, impactful, action-oriented."""

        response = client.chat.completions.create(
            model=self.deployment,
            messages=[
                {"role": "system", "content": "You are creating executive presentation content. Be concise, impactful, and focus on insights and actions."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )

        # Parse the response into structured content
        content = response.choices[0].message.content

        return {
            "title": slide_plan.title,
            "narrative": slide_plan.narrative,
            "talking_points": slide_plan.talking_points,
            "insight": slide_plan.insight,
            "visualization_type": slide_plan.visualization_type,
            "ai_content": content
        }

    async def generate_presentation_plan(
        self,
        presentation_context: Dict[str, Any],
        data_collections: List[Dict[str, Any]]
    ) -> PresentationPlan:
        """
        Main entry point: Analyze all data and generate a complete presentation plan.
        """
        logger.info(f"Starting AI presentation planning with {len(data_collections)} data collections")

        # Step 1: Analyze each data collection
        data_analyses = []
        for collection in data_collections:
            try:
                analysis = await self.analyze_data(collection, presentation_context)
                data_analyses.append(analysis)
                logger.info(f"Analyzed collection: {collection.get('title')} -> {analysis.best_visualization}")
            except Exception as e:
                logger.error(f"Error analyzing data collection: {e}")
                # Create a fallback analysis
                data_analyses.append(DataAnalysis(
                    summary=f"Data from {collection.get('title', 'unknown source')}",
                    key_insights=[],
                    best_visualization=VisualizationType.TABLE,
                    chart_title=collection.get('title', 'Data'),
                    story="Data requires further analysis."
                ))

        # Step 2: Plan the presentation
        try:
            plan = await self.plan_presentation(presentation_context, data_collections, data_analyses)
            logger.info(f"Generated presentation plan with {len(plan.slides)} slides")
            return plan
        except Exception as e:
            logger.error(f"Error planning presentation: {e}")
            # Return a basic fallback plan
            return self._create_fallback_plan(presentation_context, data_collections, data_analyses)

    def _create_fallback_plan(
        self,
        context: Dict[str, Any],
        collections: List[Dict[str, Any]],
        analyses: List[DataAnalysis]
    ) -> PresentationPlan:
        """Create a basic fallback plan if AI fails."""
        slides = []

        for collection, analysis in zip(collections, analyses):
            slides.append(SlideContent(
                title=analysis.chart_title or collection.get('title', 'Data'),
                narrative=analysis.summary,
                talking_points=[ins.insight for ins in analysis.key_insights[:5]],
                visualization_type=analysis.best_visualization,
                insight=analysis.story
            ))

        return PresentationPlan(
            executive_summary=f"Presentation covering {len(collections)} data topics.",
            key_message="Review the data and insights presented.",
            recommended_slide_count=len(slides) + 2,
            slides=slides,
            closing_recommendations=["Review findings", "Discuss next steps"]
        )


# Singleton instance
_ai_generator = None

def get_ai_generator() -> AIGenerator:
    """Get the singleton AI generator instance."""
    global _ai_generator
    if _ai_generator is None:
        _ai_generator = AIGenerator()
    return _ai_generator
