"""
PPT Assembler for v3 Architecture

This module ONLY assembles PowerPoint files from structured instructions.
It does NOT make any decisions - all intelligence comes from the Assistant.

Charts are inserted as images (PNG files generated by Code Interpreter).
"""
import logging
from io import BytesIO
from typing import Dict, List, Optional, Any

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

logger = logging.getLogger(__name__)


# Layout constants
# Chart aspect ratio: 16:9 (matches 1920x1080 render)
# Height: 4.5" -> Width: 4.5 * (16/9) = 8.0"
# Centering: (13.333 - 8.0) / 2 = 2.67"
CHART_POSITION = {
    "left": Inches(2.67),
    "top": Inches(1.5),
    "width": Inches(8.0),
    "height": Inches(4.5)
}

INSIGHT_BOX_POSITION = {
    "left": Inches(0.5),
    "top": Inches(6.3),
    "width": Inches(12.33),
    "height": Inches(0.4)
}


class PPTAssembler:
    """
    Assembles PowerPoint presentations from structured slide definitions.

    This class does NOT make any content or design decisions.
    It purely translates the Assistant's response into PowerPoint elements.
    """

    def __init__(self, template_bytes: Optional[bytes] = None, template_metadata: Optional[Dict[str, Any]] = None):
        """
        Initialize the assembler.

        Args:
            template_bytes: Optional PPTX template as bytes. If None, creates blank presentation.
            template_metadata: Optional template metadata containing layoutSelectionGuide or contentLayouts.
                              If provided, layout indices will be read from metadata instead of hardcoded defaults.
        """
        if template_bytes:
            self.prs = Presentation(BytesIO(template_bytes))
            # CRITICAL: DO NOT clear slides - this preserves the template's theme/branding
            # The slide master contains all the branding (colors, fonts, backgrounds)
            # We'll just add new slides using the template's layouts
            logger.info(f"Loaded template with {len(self.prs.slide_layouts)} layouts and {len(self.prs.slides)} existing slides")

            # Only clear existing content slides if they exist
            # But preserve the template's theme, slide masters, and layouts
            if len(self.prs.slides) > 0:
                logger.info(f"Removing {len(self.prs.slides)} existing content slides from template")
                while len(self.prs.slides) > 0:
                    rId = self.prs.slides._sldIdLst[0].rId
                    self.prs.part.drop_rel(rId)
                    del self.prs.slides._sldIdLst[0]
                logger.info("Template slides cleared, theme and layouts preserved")
        else:
            # No template provided - create blank presentation
            self.prs = Presentation()
            self.prs.slide_width = Inches(13.333)
            self.prs.slide_height = Inches(7.5)
            logger.info("Created blank presentation (no template)")

        # Store template metadata for dynamic layout lookup
        self.template_metadata = template_metadata
        self._layout_cache = {}
        self._initialize_layout_mapping()

    def _initialize_layout_mapping(self):
        """
        Initialize layout mapping from template metadata.

        Maps slide_type values used in code to layoutSelectionGuide keys:
        - "title" → "title_slide"
        - "section" / "section_header" → "section_header"
        - "title_only" / "data" → "chart_or_graph"
        - "content" / "text" / "executive_summary" / "conclusion" → "bulleted_text"
        - "two_column" / "hybrid" → "text_with_graphic"
        - "paragraph" → "paragraph_text"
        """
        # Default hardcoded fallback mapping (backward compatibility)
        self._layout_cache = {
            "title": 0,        # Title Slide
            "content": 1,      # Title and Content
            "section": 2,      # Section Header
            "two_content": 3,  # Two Content
            "two_column": 3,   # Two Column (text + graphic)
            "comparison": 4,   # Comparison
            "title_only": 5,   # Title Only
            "paragraph": 5,    # Paragraph text (uses Title Only)
            "blank": 6,        # Blank
        }

        # If template metadata is provided, extract layout indices from layoutSelectionGuide
        if self.template_metadata:
            layout_guide = self.template_metadata.get("layoutSelectionGuide") or \
                          self.template_metadata.get("contentLayouts", {})

            if layout_guide:
                logger.info("Using layout indices from template metadata")

                # Map slide types to metadata keys
                slide_type_to_guide_key = {
                    "title": "title_slide",
                    "section": "section_header",
                    "title_only": "chart_or_graph",  # Used for data slides
                    "content": "bulleted_text",      # Used for text/content slides
                    "two_column": "text_with_graphic",  # Used for text + graphic slides
                    "paragraph": "paragraph_text",      # Used for paragraph text slides
                }

                # Extract layout indices from metadata
                for layout_type, guide_key in slide_type_to_guide_key.items():
                    if guide_key in layout_guide:
                        layout_info = layout_guide[guide_key]
                        layout_index = layout_info.get("layoutIndex")
                        if layout_index is not None:
                            self._layout_cache[layout_type] = layout_index
                            logger.info(f"Layout '{layout_type}' -> index {layout_index} ({layout_info.get('layout', 'unknown')})")

                logger.info(f"Final layout mapping: {self._layout_cache}")
            else:
                logger.warning("Template metadata provided but no layoutSelectionGuide found, using defaults")
        else:
            logger.info("No template metadata provided, using hardcoded default layout indices")

    def assemble(
        self,
        slides: List[Dict[str, Any]],
        chart_files: Dict[str, bytes],
        presentation_title: str = None,
        presentation_subtitle: str = None
    ) -> bytes:
        """
        Assemble a PowerPoint from slide definitions.

        Args:
            slides: List of slide dictionaries from Assistant response
            chart_files: Dict mapping filename/file_id to PNG bytes
            presentation_title: Optional title override
            presentation_subtitle: Optional subtitle override

        Returns:
            PowerPoint file as bytes
        """
        logger.info(f"Assembling presentation with {len(slides)} slides")
        logger.info(f"Chart files available: {list(chart_files.keys())}")

        for slide_def in slides:
            self._add_slide(slide_def, chart_files)

        # Save to bytes
        buffer = BytesIO()
        self.prs.save(buffer)
        buffer.seek(0)
        return buffer.getvalue()

    def _add_slide(self, slide_def: Dict[str, Any], chart_files: Dict[str, bytes]):
        """Add a single slide based on its definition."""
        slide_type = slide_def.get("slide_type", "text")
        slide_num = slide_def.get("slide_number", 0)

        logger.info(f"Adding slide {slide_num}: {slide_type}")

        if slide_type == "title":
            self._add_title_slide(slide_def)
        elif slide_type == "data":
            self._add_data_slide(slide_def, chart_files)
        elif slide_type == "executive_summary":
            self._add_content_slide(slide_def)
        elif slide_type == "section_header":
            self._add_section_slide(slide_def)
        elif slide_type == "conclusion":
            self._add_content_slide(slide_def)
        elif slide_type == "two_column":
            self._add_two_column_slide(slide_def, chart_files)
        elif slide_type == "paragraph":
            self._add_paragraph_slide(slide_def)
        else:
            self._add_content_slide(slide_def)

    def _get_layout(self, layout_type: str):
        """
        Get a slide layout by type.

        Uses cached layout mapping that was initialized from template metadata
        (if provided) or falls back to hardcoded defaults.
        """
        idx = self._layout_cache.get(layout_type, 1)

        # Ensure we don't exceed available layouts
        if idx >= len(self.prs.slide_layouts):
            logger.warning(f"Layout index {idx} for type '{layout_type}' exceeds available layouts ({len(self.prs.slide_layouts)}). Using fallback.")
            idx = min(1, len(self.prs.slide_layouts) - 1)

        return self.prs.slide_layouts[idx]

    def _clear_placeholder_shapes(self, slide):
        """
        Remove or clear default placeholder shapes from a slide.

        This prevents "Click to edit text" and other default placeholder text
        from appearing on slides where we add custom content.

        Args:
            slide: The slide to clear placeholders from
        """
        shapes_to_remove = []

        for shape in slide.shapes:
            # Check if this is a placeholder
            if shape.is_placeholder:
                placeholder_type = shape.placeholder_format.type

                # We want to remove content placeholders (type 2) that we're not using
                # Keep title placeholders (type 1) as we explicitly set them
                # Keep subtitle placeholders (type 3) as we explicitly set them
                # Content placeholders (OBJECT = 7, TEXT = 2, CHART = 8, TABLE = 12, etc.)
                # should be removed if not explicitly used

                # Remove content-type placeholders
                if placeholder_type in (2, 7, 8, 12, 14):  # TEXT, OBJECT, CHART, TABLE, PICTURE
                    # Check if the placeholder has any text content
                    # If it's empty or has default text, mark for removal
                    try:
                        if hasattr(shape, 'text_frame') and shape.text_frame:
                            text = shape.text_frame.text.strip()
                            # Remove if empty or contains common placeholder text
                            if not text or "click" in text.lower() or "edit" in text.lower():
                                shapes_to_remove.append(shape)
                        elif hasattr(shape, 'text'):
                            text = shape.text.strip()
                            if not text or "click" in text.lower() or "edit" in text.lower():
                                shapes_to_remove.append(shape)
                        else:
                            # No text attribute, safe to remove
                            shapes_to_remove.append(shape)
                    except Exception as e:
                        # If we can't read the text, it's likely an empty placeholder
                        logger.debug(f"Could not read placeholder text: {e}")
                        shapes_to_remove.append(shape)

        # Remove the identified shapes
        for shape in shapes_to_remove:
            try:
                sp = shape._element
                sp.getparent().remove(sp)
                logger.debug(f"Removed placeholder shape: type={shape.placeholder_format.type}")
            except Exception as e:
                logger.warning(f"Failed to remove placeholder shape: {e}")

    def _add_title_slide(self, slide_def: Dict[str, Any]):
        """Add a title slide."""
        layout = self._get_layout("title")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Set subtitle (use 'or' to handle None values from JSON null)
        for shape in slide.placeholders:
            if shape.placeholder_format.idx == 1:  # Subtitle placeholder
                shape.text = slide_def.get("subtitle") or ""
                break

        # Clear any unused placeholder shapes
        self._clear_placeholder_shapes(slide)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _add_data_slide(self, slide_def: Dict[str, Any], chart_files: Dict[str, bytes]):
        """Add a data slide with chart image."""
        layout = self._get_layout("title_only")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Clear any unused placeholder shapes before adding custom content
        self._clear_placeholder_shapes(slide)

        # Insert chart image if present
        chart_file = slide_def.get("chart_file")
        if chart_file:
            image_bytes = self._find_chart_image(chart_file, chart_files)
            if image_bytes:
                self._insert_chart_image(slide, image_bytes)
            else:
                logger.warning(f"Chart file not found: {chart_file}")
                # Add placeholder text
                self._add_text_box(
                    slide,
                    f"[Chart: {chart_file}]",
                    CHART_POSITION["left"],
                    CHART_POSITION["top"],
                    CHART_POSITION["width"],
                    Inches(1)
                )

        # Add key insight box
        key_insight = slide_def.get("key_insight")
        if key_insight:
            self._add_insight_box(slide, key_insight)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _add_content_slide(self, slide_def: Dict[str, Any]):
        """Add a content slide with bullets."""
        layout = self._get_layout("content")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Set bullet points (use 'or' to handle None values from JSON null)
        bullets = slide_def.get("bullets") or []
        content_placeholder_used = False
        if bullets:
            # Find the content placeholder
            for shape in slide.placeholders:
                if shape.placeholder_format.idx == 1:  # Content placeholder
                    tf = shape.text_frame
                    tf.clear()

                    for i, bullet in enumerate(bullets):
                        if i == 0:
                            p = tf.paragraphs[0]
                        else:
                            p = tf.add_paragraph()
                        p.text = bullet or ""  # Handle None values
                        p.level = 0
                    content_placeholder_used = True
                    break

        # Clear unused placeholders (but keep the content placeholder if we used it)
        if not content_placeholder_used:
            self._clear_placeholder_shapes(slide)

        # Add key insight if no chart
        key_insight = slide_def.get("key_insight")
        if key_insight and slide_def.get("slide_type") != "data":
            self._add_insight_box(slide, key_insight)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _add_section_slide(self, slide_def: Dict[str, Any]):
        """Add a section header slide."""
        layout = self._get_layout("section")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Set subtitle if available (use 'or' to handle None values from JSON null)
        for shape in slide.placeholders:
            if shape.placeholder_format.idx == 1:
                shape.text = slide_def.get("subtitle") or ""
                break

        # Clear any unused placeholder shapes
        self._clear_placeholder_shapes(slide)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _add_two_column_slide(self, slide_def: Dict[str, Any], chart_files: Dict[str, bytes]):
        """
        Add a two-column slide with text on left and graphic on right.

        Uses the "Two column graphics right" layout with:
        - Title at top
        - Left placeholder (idx=1) for text/bullets
        - Right placeholder (idx=2) for chart image
        """
        layout = self._get_layout("two_column")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Find and populate left content placeholder (idx=1) with bullets
        bullets = slide_def.get("bullets") or []
        left_placeholder_used = False
        if bullets:
            for shape in slide.placeholders:
                if shape.placeholder_format.idx == 1:  # Left content placeholder
                    tf = shape.text_frame
                    tf.clear()

                    for i, bullet in enumerate(bullets):
                        if i == 0:
                            p = tf.paragraphs[0]
                        else:
                            p = tf.add_paragraph()
                        p.text = bullet or ""  # Handle None values
                        p.level = 0
                    left_placeholder_used = True
                    break

        # Find and populate right content placeholder (idx=2) with chart image
        chart_file = slide_def.get("chart_file")
        right_placeholder_used = False
        if chart_file:
            image_bytes = self._find_chart_image(chart_file, chart_files)
            if image_bytes:
                # Find the right placeholder (idx=2) and insert image
                for shape in slide.placeholders:
                    if shape.placeholder_format.idx == 2:  # Right content placeholder
                        # Get the placeholder's position and size
                        left = shape.left
                        top = shape.top
                        width = shape.width
                        height = shape.height

                        # Remove the placeholder
                        sp = shape._element
                        sp.getparent().remove(sp)

                        # Insert image in the same position
                        image_stream = BytesIO(image_bytes)
                        slide.shapes.add_picture(
                            image_stream,
                            left,
                            top,
                            width=width
                            # Do NOT pass height - let python-pptx preserve aspect ratio
                        )
                        right_placeholder_used = True
                        break
            else:
                logger.warning(f"Chart file not found: {chart_file}")

        # Clear unused placeholders (but keep the ones we used)
        if not left_placeholder_used and not right_placeholder_used:
            self._clear_placeholder_shapes(slide)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _add_paragraph_slide(self, slide_def: Dict[str, Any]):
        """
        Add a paragraph text slide.

        Uses the "Title Only" layout, which is versatile for paragraph text:
        - Title at top
        - Custom text box for paragraph content below title
        - Falls back to bullets if content is not provided
        """
        layout = self._get_layout("paragraph")
        slide = self.prs.slides.add_slide(layout)

        # Set title (use 'or' to handle None values from JSON null)
        if slide.shapes.title:
            slide.shapes.title.text = slide_def.get("title") or ""

        # Clear any unused placeholder shapes before adding custom content
        self._clear_placeholder_shapes(slide)

        # Check if we have paragraph content or bullets
        content = slide_def.get("content")
        bullets = slide_def.get("bullets") or []

        if content:
            # Add paragraph text as a text box
            textbox = slide.shapes.add_textbox(
                Inches(0.5),   # left
                Inches(1.5),   # top (below title)
                Inches(12.33), # width (nearly full slide width)
                Inches(5.0)    # height
            )

            tf = textbox.text_frame
            tf.word_wrap = True
            tf.vertical_anchor = MSO_ANCHOR.TOP

            p = tf.paragraphs[0]
            p.text = content or ""  # Handle None values
            p.font.size = Pt(14)
            p.alignment = PP_ALIGN.LEFT

        elif bullets:
            # Fall back to bullets if no paragraph content
            textbox = slide.shapes.add_textbox(
                Inches(0.5),
                Inches(1.5),
                Inches(12.33),
                Inches(5.0)
            )

            tf = textbox.text_frame
            tf.word_wrap = True

            for i, bullet in enumerate(bullets):
                if i == 0:
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()
                p.text = bullet or ""  # Handle None values
                p.level = 0

        # Add key insight box if present
        key_insight = slide_def.get("key_insight")
        if key_insight:
            self._add_insight_box(slide, key_insight)

        # Add speaker notes
        self._add_speaker_notes(slide, slide_def.get("speaker_notes"))

    def _find_chart_image(self, chart_file: str, chart_files: Dict[str, bytes]) -> Optional[bytes]:
        """
        Find chart image bytes by filename or file_id.

        Handles multiple naming patterns:
        - Direct match: "chart_1.png"
        - File ID: "file-abc123"
        - Without extension: "chart_1"
        - Index-based fallback
        """
        # Direct match
        if chart_file in chart_files:
            logger.info(f"Chart found (direct match): {chart_file}")
            return chart_files[chart_file]

        # Try without extension
        base_name = chart_file.replace(".png", "").replace(".jpg", "")
        for key, value in chart_files.items():
            if base_name in key or key in base_name:
                logger.info(f"Chart found (partial match): {chart_file} -> {key}")
                return value

        # Try matching by index (chart_1, chart_2, etc.)
        import re
        match = re.search(r'chart_?(\d+)', chart_file.lower())
        if match:
            idx = int(match.group(1)) - 1  # 0-indexed

            # Find the idx-th PNG file in chart_files
            png_files = [k for k in sorted(chart_files.keys()) if k.endswith('.png') or 'chart' in k.lower()]
            if idx < len(png_files):
                logger.info(f"Chart found (index match): {chart_file} -> {png_files[idx]}")
                return chart_files[png_files[idx]]

        logger.warning(f"Chart NOT found: {chart_file}. Available: {list(chart_files.keys())}")
        return None

    def _insert_chart_image(self, slide, image_bytes: bytes):
        """
        Insert a chart image onto the slide.

        IMPORTANT: Only pass width to maintain aspect ratio.
        python-pptx will auto-calculate height based on the image's aspect ratio.
        This prevents stretching of 16:9 charts.
        """
        image_stream = BytesIO(image_bytes)
        slide.shapes.add_picture(
            image_stream,
            CHART_POSITION["left"],
            CHART_POSITION["top"],
            width=CHART_POSITION["width"]
            # Do NOT pass height - let python-pptx preserve aspect ratio
        )

    def _add_insight_box(self, slide, insight: str):
        """Add a key insight callout box at the bottom of the slide."""
        textbox = slide.shapes.add_textbox(
            INSIGHT_BOX_POSITION["left"],
            INSIGHT_BOX_POSITION["top"],
            INSIGHT_BOX_POSITION["width"],
            INSIGHT_BOX_POSITION["height"]
        )

        tf = textbox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = f"KEY INSIGHT: {insight}"
        p.font.size = Pt(11)
        p.font.bold = True
        p.font.color.rgb = RGBColor(0, 51, 102)  # Dark blue

    def _add_text_box(self, slide, text: str, left, top, width, height):
        """Add a simple text box."""
        textbox = slide.shapes.add_textbox(left, top, width, height)
        tf = textbox.text_frame
        tf.text = text

    def _add_speaker_notes(self, slide, notes: Optional[str]):
        """Add speaker notes to a slide."""
        if notes:
            notes_slide = slide.notes_slide
            notes_slide.notes_text_frame.text = notes


def assemble_presentation(
    slides: List[Dict[str, Any]],
    chart_files: Dict[str, bytes],
    template_bytes: Optional[bytes] = None,
    template_metadata: Optional[Dict[str, Any]] = None,
    presentation_title: str = None,
    presentation_subtitle: str = None
) -> bytes:
    """
    Convenience function to assemble a presentation.

    Args:
        slides: List of slide definitions from Assistant response
        chart_files: Dict mapping filename/file_id to PNG bytes
        template_bytes: Optional PPTX template
        template_metadata: Optional template metadata containing layoutSelectionGuide
        presentation_title: Optional title
        presentation_subtitle: Optional subtitle

    Returns:
        PowerPoint file as bytes
    """
    assembler = PPTAssembler(template_bytes=template_bytes, template_metadata=template_metadata)
    return assembler.assemble(
        slides=slides,
        chart_files=chart_files,
        presentation_title=presentation_title,
        presentation_subtitle=presentation_subtitle
    )
